kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "enable-admission-plugins": "NodeRestriction,PodSecurityPolicy"
nodes:
- role: control-plane
  extraMounts:
  - containerPath: /kind/manifests/default-psp.yaml
    hostPath: /home/joy/project/psp/privileged-psp.yaml
    readOnly: true
- role: worker