apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: psp
  name: psp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: psp
    spec:
      containers:
      - image: alpine
        name: alpine
        command: ["sleep", "3600"]
        securityContext:
          runAsUser: 1000
        resources: {}
status: {}
